/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as prestigeLearnIntroductionRouteImport } from './routes/(prestige)/learn.introduction'
import { Route as prestigeLearnTheoryTaskRouteImport } from './routes/(prestige)/learn.theory.task'
import { Route as prestigeLearnTheorySchedulerRouteImport } from './routes/(prestige)/learn.theory.scheduler'
import { Route as prestigeLearnTheoryQueuesRouteImport } from './routes/(prestige)/learn.theory.queues'
import { Route as prestigeLearnTheoryBrowserWorkRouteImport } from './routes/(prestige)/learn.theory.browser-work'
import { Route as prestigeLearnSchedulersWorkLoopRouteImport } from './routes/(prestige)/learn.schedulers.workLoop'
import { Route as prestigeLearnSchedulersSchedulerIntroRouteImport } from './routes/(prestige)/learn.schedulers.scheduler-intro'
import { Route as prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRouteImport } from './routes/(prestige)/learn.schedulers.schedulePerformWorkUntilDeadline'
import { Route as prestigeLearnSchedulersScheduleCallbackRouteImport } from './routes/(prestige)/learn.schedulers.scheduleCallback'
import { Route as prestigeLearnSchedulersRequestHostCallbackRouteImport } from './routes/(prestige)/learn.schedulers.requestHostCallback'
import { Route as prestigeLearnSchedulersPerformWorkUntilDeadlineRouteImport } from './routes/(prestige)/learn.schedulers.performWorkUntilDeadline'
import { Route as prestigeLearnSchedulersFlushWorkRouteImport } from './routes/(prestige)/learn.schedulers.flushWork'
import { Route as prestigeLearnPrerequisitesPrerequisitesRouteImport } from './routes/(prestige)/learn.prerequisites.prerequisites'
import { Route as prestigeLearnPrerequisitesMiniHeapRouteImport } from './routes/(prestige)/learn.prerequisites.mini-heap'
import { Route as prestigeLearnPrerequisitesEventLoopRouteImport } from './routes/(prestige)/learn.prerequisites.event-loop'

const prestigeLearnLazyRouteImport = createFileRoute('/(prestige)/learn')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeLearnLazyRoute = prestigeLearnLazyRouteImport
  .update({
    id: '/(prestige)/learn',
    path: '/learn',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/learn.lazy').then((d) => d.Route))
const prestigeLearnIntroductionRoute = prestigeLearnIntroductionRouteImport
  .update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => prestigeLearnLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/learn.introduction.lazy').then((d) => d.Route),
  )
const prestigeLearnTheoryTaskRoute = prestigeLearnTheoryTaskRouteImport
  .update({
    id: '/theory/task',
    path: '/theory/task',
    getParentRoute: () => prestigeLearnLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/learn.theory.task.lazy').then((d) => d.Route),
  )
const prestigeLearnTheorySchedulerRoute =
  prestigeLearnTheorySchedulerRouteImport
    .update({
      id: '/theory/scheduler',
      path: '/theory/scheduler',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.theory.scheduler.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnTheoryQueuesRoute = prestigeLearnTheoryQueuesRouteImport
  .update({
    id: '/theory/queues',
    path: '/theory/queues',
    getParentRoute: () => prestigeLearnLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/learn.theory.queues.lazy').then((d) => d.Route),
  )
const prestigeLearnTheoryBrowserWorkRoute =
  prestigeLearnTheoryBrowserWorkRouteImport
    .update({
      id: '/theory/browser-work',
      path: '/theory/browser-work',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.theory.browser-work.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnSchedulersWorkLoopRoute =
  prestigeLearnSchedulersWorkLoopRouteImport
    .update({
      id: '/schedulers/workLoop',
      path: '/schedulers/workLoop',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.schedulers.workLoop.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnSchedulersSchedulerIntroRoute =
  prestigeLearnSchedulersSchedulerIntroRouteImport
    .update({
      id: '/schedulers/scheduler-intro',
      path: '/schedulers/scheduler-intro',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.schedulers.scheduler-intro.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRoute =
  prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRouteImport
    .update({
      id: '/schedulers/schedulePerformWorkUntilDeadline',
      path: '/schedulers/schedulePerformWorkUntilDeadline',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.schedulers.schedulePerformWorkUntilDeadline.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnSchedulersScheduleCallbackRoute =
  prestigeLearnSchedulersScheduleCallbackRouteImport
    .update({
      id: '/schedulers/scheduleCallback',
      path: '/schedulers/scheduleCallback',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.schedulers.scheduleCallback.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnSchedulersRequestHostCallbackRoute =
  prestigeLearnSchedulersRequestHostCallbackRouteImport
    .update({
      id: '/schedulers/requestHostCallback',
      path: '/schedulers/requestHostCallback',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.schedulers.requestHostCallback.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnSchedulersPerformWorkUntilDeadlineRoute =
  prestigeLearnSchedulersPerformWorkUntilDeadlineRouteImport
    .update({
      id: '/schedulers/performWorkUntilDeadline',
      path: '/schedulers/performWorkUntilDeadline',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.schedulers.performWorkUntilDeadline.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnSchedulersFlushWorkRoute =
  prestigeLearnSchedulersFlushWorkRouteImport
    .update({
      id: '/schedulers/flushWork',
      path: '/schedulers/flushWork',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.schedulers.flushWork.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnPrerequisitesPrerequisitesRoute =
  prestigeLearnPrerequisitesPrerequisitesRouteImport
    .update({
      id: '/prerequisites/prerequisites',
      path: '/prerequisites/prerequisites',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.prerequisites.prerequisites.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnPrerequisitesMiniHeapRoute =
  prestigeLearnPrerequisitesMiniHeapRouteImport
    .update({
      id: '/prerequisites/mini-heap',
      path: '/prerequisites/mini-heap',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.prerequisites.mini-heap.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnPrerequisitesEventLoopRoute =
  prestigeLearnPrerequisitesEventLoopRouteImport
    .update({
      id: '/prerequisites/event-loop',
      path: '/prerequisites/event-loop',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.prerequisites.event-loop.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof prestigeLearnLazyRouteWithChildren
  '/learn/introduction': typeof prestigeLearnIntroductionRoute
  '/learn/prerequisites/event-loop': typeof prestigeLearnPrerequisitesEventLoopRoute
  '/learn/prerequisites/mini-heap': typeof prestigeLearnPrerequisitesMiniHeapRoute
  '/learn/prerequisites/prerequisites': typeof prestigeLearnPrerequisitesPrerequisitesRoute
  '/learn/schedulers/flushWork': typeof prestigeLearnSchedulersFlushWorkRoute
  '/learn/schedulers/performWorkUntilDeadline': typeof prestigeLearnSchedulersPerformWorkUntilDeadlineRoute
  '/learn/schedulers/requestHostCallback': typeof prestigeLearnSchedulersRequestHostCallbackRoute
  '/learn/schedulers/scheduleCallback': typeof prestigeLearnSchedulersScheduleCallbackRoute
  '/learn/schedulers/schedulePerformWorkUntilDeadline': typeof prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRoute
  '/learn/schedulers/scheduler-intro': typeof prestigeLearnSchedulersSchedulerIntroRoute
  '/learn/schedulers/workLoop': typeof prestigeLearnSchedulersWorkLoopRoute
  '/learn/theory/browser-work': typeof prestigeLearnTheoryBrowserWorkRoute
  '/learn/theory/queues': typeof prestigeLearnTheoryQueuesRoute
  '/learn/theory/scheduler': typeof prestigeLearnTheorySchedulerRoute
  '/learn/theory/task': typeof prestigeLearnTheoryTaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof prestigeLearnLazyRouteWithChildren
  '/learn/introduction': typeof prestigeLearnIntroductionRoute
  '/learn/prerequisites/event-loop': typeof prestigeLearnPrerequisitesEventLoopRoute
  '/learn/prerequisites/mini-heap': typeof prestigeLearnPrerequisitesMiniHeapRoute
  '/learn/prerequisites/prerequisites': typeof prestigeLearnPrerequisitesPrerequisitesRoute
  '/learn/schedulers/flushWork': typeof prestigeLearnSchedulersFlushWorkRoute
  '/learn/schedulers/performWorkUntilDeadline': typeof prestigeLearnSchedulersPerformWorkUntilDeadlineRoute
  '/learn/schedulers/requestHostCallback': typeof prestigeLearnSchedulersRequestHostCallbackRoute
  '/learn/schedulers/scheduleCallback': typeof prestigeLearnSchedulersScheduleCallbackRoute
  '/learn/schedulers/schedulePerformWorkUntilDeadline': typeof prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRoute
  '/learn/schedulers/scheduler-intro': typeof prestigeLearnSchedulersSchedulerIntroRoute
  '/learn/schedulers/workLoop': typeof prestigeLearnSchedulersWorkLoopRoute
  '/learn/theory/browser-work': typeof prestigeLearnTheoryBrowserWorkRoute
  '/learn/theory/queues': typeof prestigeLearnTheoryQueuesRoute
  '/learn/theory/scheduler': typeof prestigeLearnTheorySchedulerRoute
  '/learn/theory/task': typeof prestigeLearnTheoryTaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(prestige)/learn': typeof prestigeLearnLazyRouteWithChildren
  '/(prestige)/learn/introduction': typeof prestigeLearnIntroductionRoute
  '/(prestige)/learn/prerequisites/event-loop': typeof prestigeLearnPrerequisitesEventLoopRoute
  '/(prestige)/learn/prerequisites/mini-heap': typeof prestigeLearnPrerequisitesMiniHeapRoute
  '/(prestige)/learn/prerequisites/prerequisites': typeof prestigeLearnPrerequisitesPrerequisitesRoute
  '/(prestige)/learn/schedulers/flushWork': typeof prestigeLearnSchedulersFlushWorkRoute
  '/(prestige)/learn/schedulers/performWorkUntilDeadline': typeof prestigeLearnSchedulersPerformWorkUntilDeadlineRoute
  '/(prestige)/learn/schedulers/requestHostCallback': typeof prestigeLearnSchedulersRequestHostCallbackRoute
  '/(prestige)/learn/schedulers/scheduleCallback': typeof prestigeLearnSchedulersScheduleCallbackRoute
  '/(prestige)/learn/schedulers/schedulePerformWorkUntilDeadline': typeof prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRoute
  '/(prestige)/learn/schedulers/scheduler-intro': typeof prestigeLearnSchedulersSchedulerIntroRoute
  '/(prestige)/learn/schedulers/workLoop': typeof prestigeLearnSchedulersWorkLoopRoute
  '/(prestige)/learn/theory/browser-work': typeof prestigeLearnTheoryBrowserWorkRoute
  '/(prestige)/learn/theory/queues': typeof prestigeLearnTheoryQueuesRoute
  '/(prestige)/learn/theory/scheduler': typeof prestigeLearnTheorySchedulerRoute
  '/(prestige)/learn/theory/task': typeof prestigeLearnTheoryTaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/learn/introduction'
    | '/learn/prerequisites/event-loop'
    | '/learn/prerequisites/mini-heap'
    | '/learn/prerequisites/prerequisites'
    | '/learn/schedulers/flushWork'
    | '/learn/schedulers/performWorkUntilDeadline'
    | '/learn/schedulers/requestHostCallback'
    | '/learn/schedulers/scheduleCallback'
    | '/learn/schedulers/schedulePerformWorkUntilDeadline'
    | '/learn/schedulers/scheduler-intro'
    | '/learn/schedulers/workLoop'
    | '/learn/theory/browser-work'
    | '/learn/theory/queues'
    | '/learn/theory/scheduler'
    | '/learn/theory/task'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learn'
    | '/learn/introduction'
    | '/learn/prerequisites/event-loop'
    | '/learn/prerequisites/mini-heap'
    | '/learn/prerequisites/prerequisites'
    | '/learn/schedulers/flushWork'
    | '/learn/schedulers/performWorkUntilDeadline'
    | '/learn/schedulers/requestHostCallback'
    | '/learn/schedulers/scheduleCallback'
    | '/learn/schedulers/schedulePerformWorkUntilDeadline'
    | '/learn/schedulers/scheduler-intro'
    | '/learn/schedulers/workLoop'
    | '/learn/theory/browser-work'
    | '/learn/theory/queues'
    | '/learn/theory/scheduler'
    | '/learn/theory/task'
  id:
    | '__root__'
    | '/'
    | '/(prestige)/learn'
    | '/(prestige)/learn/introduction'
    | '/(prestige)/learn/prerequisites/event-loop'
    | '/(prestige)/learn/prerequisites/mini-heap'
    | '/(prestige)/learn/prerequisites/prerequisites'
    | '/(prestige)/learn/schedulers/flushWork'
    | '/(prestige)/learn/schedulers/performWorkUntilDeadline'
    | '/(prestige)/learn/schedulers/requestHostCallback'
    | '/(prestige)/learn/schedulers/scheduleCallback'
    | '/(prestige)/learn/schedulers/schedulePerformWorkUntilDeadline'
    | '/(prestige)/learn/schedulers/scheduler-intro'
    | '/(prestige)/learn/schedulers/workLoop'
    | '/(prestige)/learn/theory/browser-work'
    | '/(prestige)/learn/theory/queues'
    | '/(prestige)/learn/theory/scheduler'
    | '/(prestige)/learn/theory/task'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  prestigeLearnLazyRoute: typeof prestigeLearnLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/learn': {
      id: '/(prestige)/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof prestigeLearnLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/learn/introduction': {
      id: '/(prestige)/learn/introduction'
      path: '/introduction'
      fullPath: '/learn/introduction'
      preLoaderRoute: typeof prestigeLearnIntroductionRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/theory/task': {
      id: '/(prestige)/learn/theory/task'
      path: '/theory/task'
      fullPath: '/learn/theory/task'
      preLoaderRoute: typeof prestigeLearnTheoryTaskRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/theory/scheduler': {
      id: '/(prestige)/learn/theory/scheduler'
      path: '/theory/scheduler'
      fullPath: '/learn/theory/scheduler'
      preLoaderRoute: typeof prestigeLearnTheorySchedulerRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/theory/queues': {
      id: '/(prestige)/learn/theory/queues'
      path: '/theory/queues'
      fullPath: '/learn/theory/queues'
      preLoaderRoute: typeof prestigeLearnTheoryQueuesRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/theory/browser-work': {
      id: '/(prestige)/learn/theory/browser-work'
      path: '/theory/browser-work'
      fullPath: '/learn/theory/browser-work'
      preLoaderRoute: typeof prestigeLearnTheoryBrowserWorkRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/schedulers/workLoop': {
      id: '/(prestige)/learn/schedulers/workLoop'
      path: '/schedulers/workLoop'
      fullPath: '/learn/schedulers/workLoop'
      preLoaderRoute: typeof prestigeLearnSchedulersWorkLoopRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/schedulers/scheduler-intro': {
      id: '/(prestige)/learn/schedulers/scheduler-intro'
      path: '/schedulers/scheduler-intro'
      fullPath: '/learn/schedulers/scheduler-intro'
      preLoaderRoute: typeof prestigeLearnSchedulersSchedulerIntroRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/schedulers/schedulePerformWorkUntilDeadline': {
      id: '/(prestige)/learn/schedulers/schedulePerformWorkUntilDeadline'
      path: '/schedulers/schedulePerformWorkUntilDeadline'
      fullPath: '/learn/schedulers/schedulePerformWorkUntilDeadline'
      preLoaderRoute: typeof prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/schedulers/scheduleCallback': {
      id: '/(prestige)/learn/schedulers/scheduleCallback'
      path: '/schedulers/scheduleCallback'
      fullPath: '/learn/schedulers/scheduleCallback'
      preLoaderRoute: typeof prestigeLearnSchedulersScheduleCallbackRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/schedulers/requestHostCallback': {
      id: '/(prestige)/learn/schedulers/requestHostCallback'
      path: '/schedulers/requestHostCallback'
      fullPath: '/learn/schedulers/requestHostCallback'
      preLoaderRoute: typeof prestigeLearnSchedulersRequestHostCallbackRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/schedulers/performWorkUntilDeadline': {
      id: '/(prestige)/learn/schedulers/performWorkUntilDeadline'
      path: '/schedulers/performWorkUntilDeadline'
      fullPath: '/learn/schedulers/performWorkUntilDeadline'
      preLoaderRoute: typeof prestigeLearnSchedulersPerformWorkUntilDeadlineRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/schedulers/flushWork': {
      id: '/(prestige)/learn/schedulers/flushWork'
      path: '/schedulers/flushWork'
      fullPath: '/learn/schedulers/flushWork'
      preLoaderRoute: typeof prestigeLearnSchedulersFlushWorkRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/prerequisites/prerequisites': {
      id: '/(prestige)/learn/prerequisites/prerequisites'
      path: '/prerequisites/prerequisites'
      fullPath: '/learn/prerequisites/prerequisites'
      preLoaderRoute: typeof prestigeLearnPrerequisitesPrerequisitesRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/prerequisites/mini-heap': {
      id: '/(prestige)/learn/prerequisites/mini-heap'
      path: '/prerequisites/mini-heap'
      fullPath: '/learn/prerequisites/mini-heap'
      preLoaderRoute: typeof prestigeLearnPrerequisitesMiniHeapRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/prerequisites/event-loop': {
      id: '/(prestige)/learn/prerequisites/event-loop'
      path: '/prerequisites/event-loop'
      fullPath: '/learn/prerequisites/event-loop'
      preLoaderRoute: typeof prestigeLearnPrerequisitesEventLoopRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
  }
}

interface prestigeLearnLazyRouteChildren {
  prestigeLearnIntroductionRoute: typeof prestigeLearnIntroductionRoute
  prestigeLearnPrerequisitesEventLoopRoute: typeof prestigeLearnPrerequisitesEventLoopRoute
  prestigeLearnPrerequisitesMiniHeapRoute: typeof prestigeLearnPrerequisitesMiniHeapRoute
  prestigeLearnPrerequisitesPrerequisitesRoute: typeof prestigeLearnPrerequisitesPrerequisitesRoute
  prestigeLearnSchedulersFlushWorkRoute: typeof prestigeLearnSchedulersFlushWorkRoute
  prestigeLearnSchedulersPerformWorkUntilDeadlineRoute: typeof prestigeLearnSchedulersPerformWorkUntilDeadlineRoute
  prestigeLearnSchedulersRequestHostCallbackRoute: typeof prestigeLearnSchedulersRequestHostCallbackRoute
  prestigeLearnSchedulersScheduleCallbackRoute: typeof prestigeLearnSchedulersScheduleCallbackRoute
  prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRoute: typeof prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRoute
  prestigeLearnSchedulersSchedulerIntroRoute: typeof prestigeLearnSchedulersSchedulerIntroRoute
  prestigeLearnSchedulersWorkLoopRoute: typeof prestigeLearnSchedulersWorkLoopRoute
  prestigeLearnTheoryBrowserWorkRoute: typeof prestigeLearnTheoryBrowserWorkRoute
  prestigeLearnTheoryQueuesRoute: typeof prestigeLearnTheoryQueuesRoute
  prestigeLearnTheorySchedulerRoute: typeof prestigeLearnTheorySchedulerRoute
  prestigeLearnTheoryTaskRoute: typeof prestigeLearnTheoryTaskRoute
}

const prestigeLearnLazyRouteChildren: prestigeLearnLazyRouteChildren = {
  prestigeLearnIntroductionRoute: prestigeLearnIntroductionRoute,
  prestigeLearnPrerequisitesEventLoopRoute:
    prestigeLearnPrerequisitesEventLoopRoute,
  prestigeLearnPrerequisitesMiniHeapRoute:
    prestigeLearnPrerequisitesMiniHeapRoute,
  prestigeLearnPrerequisitesPrerequisitesRoute:
    prestigeLearnPrerequisitesPrerequisitesRoute,
  prestigeLearnSchedulersFlushWorkRoute: prestigeLearnSchedulersFlushWorkRoute,
  prestigeLearnSchedulersPerformWorkUntilDeadlineRoute:
    prestigeLearnSchedulersPerformWorkUntilDeadlineRoute,
  prestigeLearnSchedulersRequestHostCallbackRoute:
    prestigeLearnSchedulersRequestHostCallbackRoute,
  prestigeLearnSchedulersScheduleCallbackRoute:
    prestigeLearnSchedulersScheduleCallbackRoute,
  prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRoute:
    prestigeLearnSchedulersSchedulePerformWorkUntilDeadlineRoute,
  prestigeLearnSchedulersSchedulerIntroRoute:
    prestigeLearnSchedulersSchedulerIntroRoute,
  prestigeLearnSchedulersWorkLoopRoute: prestigeLearnSchedulersWorkLoopRoute,
  prestigeLearnTheoryBrowserWorkRoute: prestigeLearnTheoryBrowserWorkRoute,
  prestigeLearnTheoryQueuesRoute: prestigeLearnTheoryQueuesRoute,
  prestigeLearnTheorySchedulerRoute: prestigeLearnTheorySchedulerRoute,
  prestigeLearnTheoryTaskRoute: prestigeLearnTheoryTaskRoute,
}

const prestigeLearnLazyRouteWithChildren =
  prestigeLearnLazyRoute._addFileChildren(prestigeLearnLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  prestigeLearnLazyRoute: prestigeLearnLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
