/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as prestigeLearnShowcaseRouteImport } from './routes/(prestige)/learn.showcase'
import { Route as prestigeLearnPrerequisitesMiniHeapRouteImport } from './routes/(prestige)/learn.prerequisites.mini-heap'

const prestigeLearnLazyRouteImport = createFileRoute('/(prestige)/learn')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeLearnLazyRoute = prestigeLearnLazyRouteImport
  .update({
    id: '/(prestige)/learn',
    path: '/learn',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/learn.lazy').then((d) => d.Route))
const prestigeLearnShowcaseRoute = prestigeLearnShowcaseRouteImport
  .update({
    id: '/showcase',
    path: '/showcase',
    getParentRoute: () => prestigeLearnLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/learn.showcase.lazy').then((d) => d.Route),
  )
const prestigeLearnPrerequisitesMiniHeapRoute =
  prestigeLearnPrerequisitesMiniHeapRouteImport
    .update({
      id: '/prerequisites/mini-heap',
      path: '/prerequisites/mini-heap',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.prerequisites.mini-heap.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof prestigeLearnLazyRouteWithChildren
  '/learn/showcase': typeof prestigeLearnShowcaseRoute
  '/learn/prerequisites/mini-heap': typeof prestigeLearnPrerequisitesMiniHeapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof prestigeLearnLazyRouteWithChildren
  '/learn/showcase': typeof prestigeLearnShowcaseRoute
  '/learn/prerequisites/mini-heap': typeof prestigeLearnPrerequisitesMiniHeapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(prestige)/learn': typeof prestigeLearnLazyRouteWithChildren
  '/(prestige)/learn/showcase': typeof prestigeLearnShowcaseRoute
  '/(prestige)/learn/prerequisites/mini-heap': typeof prestigeLearnPrerequisitesMiniHeapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/learn/showcase'
    | '/learn/prerequisites/mini-heap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn' | '/learn/showcase' | '/learn/prerequisites/mini-heap'
  id:
    | '__root__'
    | '/'
    | '/(prestige)/learn'
    | '/(prestige)/learn/showcase'
    | '/(prestige)/learn/prerequisites/mini-heap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  prestigeLearnLazyRoute: typeof prestigeLearnLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/learn': {
      id: '/(prestige)/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof prestigeLearnLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/learn/showcase': {
      id: '/(prestige)/learn/showcase'
      path: '/showcase'
      fullPath: '/learn/showcase'
      preLoaderRoute: typeof prestigeLearnShowcaseRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/prerequisites/mini-heap': {
      id: '/(prestige)/learn/prerequisites/mini-heap'
      path: '/prerequisites/mini-heap'
      fullPath: '/learn/prerequisites/mini-heap'
      preLoaderRoute: typeof prestigeLearnPrerequisitesMiniHeapRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
  }
}

interface prestigeLearnLazyRouteChildren {
  prestigeLearnShowcaseRoute: typeof prestigeLearnShowcaseRoute
  prestigeLearnPrerequisitesMiniHeapRoute: typeof prestigeLearnPrerequisitesMiniHeapRoute
}

const prestigeLearnLazyRouteChildren: prestigeLearnLazyRouteChildren = {
  prestigeLearnShowcaseRoute: prestigeLearnShowcaseRoute,
  prestigeLearnPrerequisitesMiniHeapRoute:
    prestigeLearnPrerequisitesMiniHeapRoute,
}

const prestigeLearnLazyRouteWithChildren =
  prestigeLearnLazyRoute._addFileChildren(prestigeLearnLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  prestigeLearnLazyRoute: prestigeLearnLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
