/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as prestigeLearnIntroductionRouteImport } from './routes/(prestige)/learn.introduction'
import { Route as prestigeLearnPrerequisitesPrerequisitesRouteImport } from './routes/(prestige)/learn.prerequisites.prerequisites'
import { Route as prestigeLearnPrerequisitesEventLoopRouteImport } from './routes/(prestige)/learn.prerequisites.event-loop'

const prestigeLearnLazyRouteImport = createFileRoute('/(prestige)/learn')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeLearnLazyRoute = prestigeLearnLazyRouteImport
  .update({
    id: '/(prestige)/learn',
    path: '/learn',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/learn.lazy').then((d) => d.Route))
const prestigeLearnIntroductionRoute = prestigeLearnIntroductionRouteImport
  .update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => prestigeLearnLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/learn.introduction.lazy').then((d) => d.Route),
  )
const prestigeLearnPrerequisitesPrerequisitesRoute =
  prestigeLearnPrerequisitesPrerequisitesRouteImport
    .update({
      id: '/prerequisites/prerequisites',
      path: '/prerequisites/prerequisites',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.prerequisites.prerequisites.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeLearnPrerequisitesEventLoopRoute =
  prestigeLearnPrerequisitesEventLoopRouteImport
    .update({
      id: '/prerequisites/event-loop',
      path: '/prerequisites/event-loop',
      getParentRoute: () => prestigeLearnLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/learn.prerequisites.event-loop.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof prestigeLearnLazyRouteWithChildren
  '/learn/introduction': typeof prestigeLearnIntroductionRoute
  '/learn/prerequisites/event-loop': typeof prestigeLearnPrerequisitesEventLoopRoute
  '/learn/prerequisites/prerequisites': typeof prestigeLearnPrerequisitesPrerequisitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof prestigeLearnLazyRouteWithChildren
  '/learn/introduction': typeof prestigeLearnIntroductionRoute
  '/learn/prerequisites/event-loop': typeof prestigeLearnPrerequisitesEventLoopRoute
  '/learn/prerequisites/prerequisites': typeof prestigeLearnPrerequisitesPrerequisitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(prestige)/learn': typeof prestigeLearnLazyRouteWithChildren
  '/(prestige)/learn/introduction': typeof prestigeLearnIntroductionRoute
  '/(prestige)/learn/prerequisites/event-loop': typeof prestigeLearnPrerequisitesEventLoopRoute
  '/(prestige)/learn/prerequisites/prerequisites': typeof prestigeLearnPrerequisitesPrerequisitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/learn/introduction'
    | '/learn/prerequisites/event-loop'
    | '/learn/prerequisites/prerequisites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learn'
    | '/learn/introduction'
    | '/learn/prerequisites/event-loop'
    | '/learn/prerequisites/prerequisites'
  id:
    | '__root__'
    | '/'
    | '/(prestige)/learn'
    | '/(prestige)/learn/introduction'
    | '/(prestige)/learn/prerequisites/event-loop'
    | '/(prestige)/learn/prerequisites/prerequisites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  prestigeLearnLazyRoute: typeof prestigeLearnLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/learn': {
      id: '/(prestige)/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof prestigeLearnLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/learn/introduction': {
      id: '/(prestige)/learn/introduction'
      path: '/introduction'
      fullPath: '/learn/introduction'
      preLoaderRoute: typeof prestigeLearnIntroductionRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/prerequisites/prerequisites': {
      id: '/(prestige)/learn/prerequisites/prerequisites'
      path: '/prerequisites/prerequisites'
      fullPath: '/learn/prerequisites/prerequisites'
      preLoaderRoute: typeof prestigeLearnPrerequisitesPrerequisitesRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
    '/(prestige)/learn/prerequisites/event-loop': {
      id: '/(prestige)/learn/prerequisites/event-loop'
      path: '/prerequisites/event-loop'
      fullPath: '/learn/prerequisites/event-loop'
      preLoaderRoute: typeof prestigeLearnPrerequisitesEventLoopRouteImport
      parentRoute: typeof prestigeLearnLazyRoute
    }
  }
}

interface prestigeLearnLazyRouteChildren {
  prestigeLearnIntroductionRoute: typeof prestigeLearnIntroductionRoute
  prestigeLearnPrerequisitesEventLoopRoute: typeof prestigeLearnPrerequisitesEventLoopRoute
  prestigeLearnPrerequisitesPrerequisitesRoute: typeof prestigeLearnPrerequisitesPrerequisitesRoute
}

const prestigeLearnLazyRouteChildren: prestigeLearnLazyRouteChildren = {
  prestigeLearnIntroductionRoute: prestigeLearnIntroductionRoute,
  prestigeLearnPrerequisitesEventLoopRoute:
    prestigeLearnPrerequisitesEventLoopRoute,
  prestigeLearnPrerequisitesPrerequisitesRoute:
    prestigeLearnPrerequisitesPrerequisitesRoute,
}

const prestigeLearnLazyRouteWithChildren =
  prestigeLearnLazyRoute._addFileChildren(prestigeLearnLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  prestigeLearnLazyRoute: prestigeLearnLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
